version: '3'

services:
  postgres-playbook:
    container_name: postgres-playbook
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres-playbook-data:/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - app-connect
    ports:
      - "5439:5432"


volumes:
      postgres-playbook-data:

networks:
  app-connect:
      driver: bridge
